name: devrev_sdk_flutter_sample
description: "A sample app to demonstrate the usage of the DevRev SDK Flutter plugin."
publish_to: 'none'

environment:
  sdk: ^3.7.0-209.0.dev

dependencies:
  flutter:
    sdk: flutter
  devrev_sdk_flutter: ^2.2.0-beta.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_app_installations: ^0.3.2+4
  firebase_messaging: ^15.2.4
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
